' <auto-generated/>
' TODO: Check VB does not support Line Directive Trivia, Original Directive #line hidden
Imports Microsoft.AspNetCore.Components

Namespace [Shared]
    Partial Public Class SurveyPrompt
        Inherits ComponentBase
        Private Sub __RazorDirectiveTokenHelpers__()
        End Sub
        Private Shared __o As Object = Nothing
        Protected Overrides Sub BuildRenderTree(ByVal __builder As Rendering.RenderTreeBuilder)
            __o = Title
        End Sub
        <Parameter>
        Public Property Title As String
    End Class
End Namespace