' <auto-generated/>
' TODO: Check VB does not support Line Directive Trivia, Original Directive #line hidden    Imports System
Imports BlazorVB.Shared
Imports Microsoft.AspNetCore.Components
Imports Microsoft.AspNetCore.Components.Routing

Partial Public Class App
    Inherits ComponentBase
    Private Sub __RazorDirectiveTokenHelpers__()
    End Sub
    Private Shared __o As Object = Nothing
    Protected Overrides Sub BuildRenderTree(ByVal __builder As Rendering.RenderTreeBuilder)
        __o = CompilerServices.RuntimeHelpers.TypeCheck(GetType(Program).Assembly)
        __o = CompilerServices.RuntimeHelpers.TypeCheck(True)
        __builder.AddAttribute(-1, "Found", CType(Function(routeData) Sub(__builder2)
                                                                          __o = CompilerServices.RuntimeHelpers.TypeCheck(routeData)
                                                                          __o = CompilerServices.RuntimeHelpers.TypeCheck(Of Type)(GetType(MainLayout))
                                                                          __builder2.AddAttribute(-1, "ChildContent", CType(Sub(__builder3)
                                                                                                                            End Sub, RenderFragment))
                                                                          __o = GetType(RouteView)
                                                                      End Sub, RenderFragment(Of RouteData)))
        __builder.AddAttribute(-1, "NotFound", CType(Sub(__builder2)
                                                         __o = CompilerServices.RuntimeHelpers.TypeCheck(Of Type)(GetType(MainLayout))
                                                         __builder2.AddAttribute(-1, "ChildContent", CType(Sub(__builder3)
                                                                                                           End Sub, RenderFragment))
                                                         __o = GetType(LayoutView)
                                                     End Sub, RenderFragment))
        __o = GetType(Router)
    End Sub
End Class
